name: hosted-pure-workflow
on: [push]

jobs:
  job:
    name: kotlin test
    runs-on: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: test
        run: kotlin -e 'System.getProperty("kotlin.home")'
        shell: bash
