name: hosted-pure-workflow
on: [push]

jobs:
  job:
    name: kotlin test
    runs-on: windows-latest
    steps:
      - name: test
        run: kotlinc -e 'System.getProperty("kotlin.home")'
        shell: bash
